apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-optimization
  namespace: production
  labels:
    app: delivery-optimization
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delivery-optimization
  template:
    metadata:
      labels:
        app: delivery-optimization
    spec:
      containers:
        - name: delivery-optimization
          image: prathicksha15/delivery-optimization:IMAGE_TAG
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-optimization-svc
  namespace: production
spec:
  selector:
    app: delivery-optimization
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
